adding revert and clean up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,31 @@ commands:
             aws s3 rm s3://<< parameters.frontend_workflowID >> --recursive
             aws cloudformation delete-stack --stack-name << parameters.frontend_workflowID >> 
           when: on_fail
+  
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      Workflow_ID:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Add parameter here     
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          name: Revert migrations
+          when: on_fail
+          command: |
+            SUCCESS=$(curl --insecure https://kvdb.io/486vPYSoxHfrrU6Z6AKf6e/migration_<< parameters.Workflow_ID >>)
+            echo SUCCESS
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+              exit 1
+            fi  
 
 orbs: 
   slack: circleci/slack@4.9.4
@@ -388,6 +413,7 @@ jobs:
       - destroy-environment: 
               frontend_workflowID : "udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
               backend_workflowID: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" 
+      - revert-migrations
   cloudfront-update:
     docker:
       # Docker image here that supports AWS CLI
@@ -408,39 +434,72 @@ jobs:
               --stack-name InitialStack \
               --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
               --tags project=udapeople
+              echo Current WorkFlowID: "${CIRCLE_WORKFLOW_ID:0:7}"
       # Here's where you will add some code to rollback on failure    
+  cleanup:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Fetch old stack workflow id
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            # fetch all stacks names   
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            
+            echo Stack names: "${STACKS[@]}"    
+            
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+            echo "clean up"
+            aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
+            aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+            aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            else
+            echo "no stacks found"
+            fi  
 
 workflows:
   default:
     jobs:
-     #- build-frontend
-     #- build-backend
-     #- test-frontend:
-        #requires: [build-frontend]
-     #- test-backend:
-        #requires: [build-backend]
-     #- scan-backend:
-        #requires: [build-backend]
-        #context: Notification
-     # - scan-frontend:
-        #  requires: [build-frontend]
-         # context: Notification
-     #- deploy-infrastructure:
-        #requires: [test-frontend, test-backend] #scan-frontend, scan-backend]
-        #filters:
-          #branches:
-            #only: [test-feature-branch]
-     #- configure-infrastructure:
-          #requires: [deploy-infrastructure]
-     #- run-migrations:
-          #requires: [configure-infrastructure]
-     #- deploy-frontend:
-          #requires: [run-migrations]
-     #- deploy-backend:
-          #requires: [run-migrations]
-     #- smoke-test:
-          #requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update
+     - build-frontend
+     - build-backend
+     - test-frontend:
+        requires: [build-frontend]
+     - test-backend:
+        requires: [build-backend]
+     - scan-backend:
+        requires: [build-backend]
+        context: Notification
+      - scan-frontend:
+          requires: [build-frontend]
+          context: Notification
+     - deploy-infrastructure:
+        requires: [test-frontend, test-backend] #scan-frontend, scan-backend]
+        filters:
+          branches:
+            only: [test-feature-branch]
+     - configure-infrastructure:
+          requires: [deploy-infrastructure]
+     - run-migrations:
+          requires: [configure-infrastructure]
+     - deploy-frontend:
+          requires: [run-migrations]
+     - deploy-backend:
+          requires: [run-migrations]
+     - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
+      #- cleanup:
+          #requires: [cloudfront-update]
+      
 
             
 
